version: '3'

services:
  app:
    container_name: docker-nextjs-typescript
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=5555
    ports:
      - 5555:5555
